/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package timetable.management;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author TARUN
 */
public class Table extends javax.swing.JFrame {

    /**
     * Creates new form Table
     */
    String url;
    Connection connection=null;
    PreparedStatement preStat;
    String Day,L1,L2,L3,L4,L5,L6;
    public Table() throws SQLException {
        initComponents();
        System.out.print("in constructor");
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TeacherTable.class.getName()).log(Level.SEVERE, null, ex);
        }

            url = "jdbc:mysql://localhost:3306/timetable";
            connection = DriverManager.getConnection(url, "root", "root");
        String query = "SELECT * FROM timetable";
        preStat = connection.prepareStatement(query);
            int i=0;
            ResultSet result = preStat.executeQuery();
            while(result.next())
            {
                ++i;
                Day=result.getString("day");
                L1=result.getString("lacture1");
                L2=result.getString("lacture2");
                L3=result.getString("lacture3");
                L4=result.getString("lacture4");
                L5=result.getString("lacture5");
                L6=result.getString("lacture6");
                switch(i)
                {
                    case 1:
                        L1D1.setText(L1);
                        L2D1.setText(L2);
                        L3D1.setText(L3);
                        L4D1.setText(L4);
                        L5D1.setText(L5);
                        L6D1.setText(L5);
                        break;
                    case 2:
                        L1D2.setText(L1);
                        L2D2.setText(L2);
                        L3D2.setText(L3);
                        L4D2.setText(L4);
                        L5D2.setText(L5);
                        L6D2.setText(L5);
                        break;
                    case 3:
                        L1D3.setText(L1);
                        L2D3.setText(L2);
                        L3D3.setText(L3);
                        L4D3.setText(L4);
                        L5D3.setText(L5);
                        L6D3.setText(L5);
                        break;
                    case 4:
                        L1D4.setText(L1);
                        L2D4.setText(L2);
                        L3D4.setText(L3);
                        L4D4.setText(L4);
                        L5D4.setText(L5);
                        L6D4.setText(L5);
                        break;
                    case 5:
                        L1D5.setText(L1);
                        L2D5.setText(L2);
                        L3D5.setText(L3);
                        L4D5.setText(L4);
                        L5D5.setText(L5);
                        L6D5.setText(L5);
                        break;
                    case 6:
                        L1D6.setText(L1);
                        L2D6.setText(L2);
                        L3D6.setText(L3);
                        L4D6.setText(L4);
                        L5D6.setText(L5);
                        L6D6.setText(L5);
                        break;
                    case 7:
                        L1D7.setText(L1);
                        L2D7.setText(L2);
                        L3D7.setText(L3);
                        L4D7.setText(L4);
                        L5D7.setText(L5);
                        L6D7.setText(L5);
                        break;
                }
                
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        day = new javax.swing.JLabel();
        day1 = new javax.swing.JLabel();
        day2 = new javax.swing.JLabel();
        day3 = new javax.swing.JLabel();
        day4 = new javax.swing.JLabel();
        day5 = new javax.swing.JLabel();
        day6 = new javax.swing.JLabel();
        day7 = new javax.swing.JLabel();
        L1D1 = new javax.swing.JLabel();
        L2D1 = new javax.swing.JLabel();
        L3D1 = new javax.swing.JLabel();
        L4D1 = new javax.swing.JLabel();
        L5D1 = new javax.swing.JLabel();
        L6D1 = new javax.swing.JLabel();
        L1D2 = new javax.swing.JLabel();
        L2D2 = new javax.swing.JLabel();
        L3D2 = new javax.swing.JLabel();
        L4D2 = new javax.swing.JLabel();
        L5D2 = new javax.swing.JLabel();
        L6D2 = new javax.swing.JLabel();
        L1D3 = new javax.swing.JLabel();
        L2D3 = new javax.swing.JLabel();
        L3D3 = new javax.swing.JLabel();
        L4D3 = new javax.swing.JLabel();
        L5D3 = new javax.swing.JLabel();
        L6D3 = new javax.swing.JLabel();
        L1D4 = new javax.swing.JLabel();
        L2D4 = new javax.swing.JLabel();
        L3D4 = new javax.swing.JLabel();
        L4D4 = new javax.swing.JLabel();
        L5D4 = new javax.swing.JLabel();
        L6D4 = new javax.swing.JLabel();
        lacture1 = new javax.swing.JLabel();
        lacture2 = new javax.swing.JLabel();
        lacture3 = new javax.swing.JLabel();
        lacture4 = new javax.swing.JLabel();
        lacture5 = new javax.swing.JLabel();
        lacture6 = new javax.swing.JLabel();
        L1D5 = new javax.swing.JLabel();
        L3D5 = new javax.swing.JLabel();
        L4D5 = new javax.swing.JLabel();
        L5D5 = new javax.swing.JLabel();
        L6D5 = new javax.swing.JLabel();
        L1D6 = new javax.swing.JLabel();
        L2D5 = new javax.swing.JLabel();
        L2D6 = new javax.swing.JLabel();
        L3D6 = new javax.swing.JLabel();
        L4D6 = new javax.swing.JLabel();
        L5D6 = new javax.swing.JLabel();
        L6D6 = new javax.swing.JLabel();
        L1D7 = new javax.swing.JLabel();
        L2D7 = new javax.swing.JLabel();
        L3D7 = new javax.swing.JLabel();
        L4D7 = new javax.swing.JLabel();
        L5D7 = new javax.swing.JLabel();
        L6D7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Timetable");
        setBackground(new java.awt.Color(0, 153, 0));
        setResizable(false);

        day.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        day.setText("Day");

        day1.setBackground(new java.awt.Color(51, 51, 255));
        day1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        day1.setText("Monday");

        day2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        day2.setText("Tuesday");

        day3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        day3.setText("Wednesday");

        day4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        day4.setText("Thursday");

        day5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        day5.setText("Friday");

        day6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        day6.setText("Saturday");

        day7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        day7.setText("Sunday");

        L1D1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        L1D1.setText("-----");

        L2D1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        L2D1.setText("-----");

        L3D1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        L3D1.setText("-----");

        L4D1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        L4D1.setText("Break");

        L5D1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        L5D1.setText("-----");

        L6D1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        L6D1.setText("-----");

        L1D2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        L2D2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        L3D2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        L4D2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        L5D2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        L6D2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        L1D3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        L2D3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        L3D3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        L4D3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        L5D3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        L6D3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        L1D4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        L2D4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        L3D4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        L4D4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        L5D4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        L6D4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lacture1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lacture1.setText("8-9 AM");

        lacture2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lacture2.setText("9-10 AM");

        lacture3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lacture3.setText("10-11 AM");

        lacture4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lacture4.setText("11-12 AM");

        lacture5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lacture5.setText("12-1 PM");

        lacture6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lacture6.setText("1-2 PM");

        L1D5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        L3D5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        L4D5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        L5D5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        L6D5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        L1D6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        L2D5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        L2D6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        L3D6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        L4D6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        L5D6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        L6D6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        L1D7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        L2D7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        L3D7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        L4D7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        L5D7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        L6D7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(day1)
                    .addComponent(day7)
                    .addComponent(day6)
                    .addComponent(day5)
                    .addComponent(day4)
                    .addComponent(day3)
                    .addComponent(day2)
                    .addComponent(day, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L1D1)
                    .addComponent(L1D2)
                    .addComponent(L1D3)
                    .addComponent(L1D4)
                    .addComponent(lacture1)
                    .addComponent(L1D5)
                    .addComponent(L1D6)
                    .addComponent(L1D7))
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L2D1)
                    .addComponent(L2D2)
                    .addComponent(L2D3)
                    .addComponent(L2D4)
                    .addComponent(lacture2)
                    .addComponent(L2D5)
                    .addComponent(L2D6)
                    .addComponent(L2D7))
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L3D1)
                    .addComponent(L3D2)
                    .addComponent(L3D3)
                    .addComponent(L3D4)
                    .addComponent(lacture3)
                    .addComponent(L3D5)
                    .addComponent(L3D6)
                    .addComponent(L3D7))
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L4D1)
                    .addComponent(lacture4)
                    .addComponent(L4D2)
                    .addComponent(L4D3)
                    .addComponent(L4D4)
                    .addComponent(L4D5)
                    .addComponent(L4D6)
                    .addComponent(L4D7))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L5D1)
                    .addComponent(lacture5)
                    .addComponent(L5D2)
                    .addComponent(L5D3)
                    .addComponent(L5D4)
                    .addComponent(L5D5)
                    .addComponent(L5D6)
                    .addComponent(L5D7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lacture6)
                        .addGap(71, 71, 71))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(L6D1)
                            .addComponent(L6D2)
                            .addComponent(L6D3)
                            .addComponent(L6D4)
                            .addComponent(L6D5)
                            .addComponent(L6D6)
                            .addComponent(L6D7))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(day, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lacture1)
                    .addComponent(lacture2)
                    .addComponent(lacture3)
                    .addComponent(lacture4)
                    .addComponent(lacture5)
                    .addComponent(lacture6))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(day1)
                    .addComponent(L1D1)
                    .addComponent(L2D1)
                    .addComponent(L3D1)
                    .addComponent(L4D1)
                    .addComponent(L5D1)
                    .addComponent(L6D1))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(day2)
                    .addComponent(L1D2)
                    .addComponent(L2D2)
                    .addComponent(L3D2)
                    .addComponent(L4D2)
                    .addComponent(L5D2)
                    .addComponent(L6D2))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(day3)
                    .addComponent(L1D3)
                    .addComponent(L2D3)
                    .addComponent(L3D3)
                    .addComponent(L4D3)
                    .addComponent(L5D3)
                    .addComponent(L6D3))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(day4)
                    .addComponent(L1D4)
                    .addComponent(L2D4)
                    .addComponent(L3D4)
                    .addComponent(L4D4)
                    .addComponent(L5D4)
                    .addComponent(L6D4))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(day5)
                    .addComponent(L1D5)
                    .addComponent(L6D5)
                    .addComponent(L2D5)
                    .addComponent(L3D5)
                    .addComponent(L4D5)
                    .addComponent(L5D5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(day6)
                    .addComponent(L1D6)
                    .addComponent(L2D6)
                    .addComponent(L3D6)
                    .addComponent(L4D6)
                    .addComponent(L5D6)
                    .addComponent(L6D6))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(day7)
                    .addComponent(L1D7)
                    .addComponent(L2D7)
                    .addComponent(L3D7)
                    .addComponent(L4D7)
                    .addComponent(L5D7)
                    .addComponent(L6D7))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L1D1;
    private javax.swing.JLabel L1D2;
    private javax.swing.JLabel L1D3;
    private javax.swing.JLabel L1D4;
    private javax.swing.JLabel L1D5;
    private javax.swing.JLabel L1D6;
    private javax.swing.JLabel L1D7;
    private javax.swing.JLabel L2D1;
    private javax.swing.JLabel L2D2;
    private javax.swing.JLabel L2D3;
    private javax.swing.JLabel L2D4;
    private javax.swing.JLabel L2D5;
    private javax.swing.JLabel L2D6;
    private javax.swing.JLabel L2D7;
    private javax.swing.JLabel L3D1;
    private javax.swing.JLabel L3D2;
    private javax.swing.JLabel L3D3;
    private javax.swing.JLabel L3D4;
    private javax.swing.JLabel L3D5;
    private javax.swing.JLabel L3D6;
    private javax.swing.JLabel L3D7;
    private javax.swing.JLabel L4D1;
    private javax.swing.JLabel L4D2;
    private javax.swing.JLabel L4D3;
    private javax.swing.JLabel L4D4;
    private javax.swing.JLabel L4D5;
    private javax.swing.JLabel L4D6;
    private javax.swing.JLabel L4D7;
    private javax.swing.JLabel L5D1;
    private javax.swing.JLabel L5D2;
    private javax.swing.JLabel L5D3;
    private javax.swing.JLabel L5D4;
    private javax.swing.JLabel L5D5;
    private javax.swing.JLabel L5D6;
    private javax.swing.JLabel L5D7;
    private javax.swing.JLabel L6D1;
    private javax.swing.JLabel L6D2;
    private javax.swing.JLabel L6D3;
    private javax.swing.JLabel L6D4;
    private javax.swing.JLabel L6D5;
    private javax.swing.JLabel L6D6;
    private javax.swing.JLabel L6D7;
    private javax.swing.JLabel day;
    private javax.swing.JLabel day1;
    private javax.swing.JLabel day2;
    private javax.swing.JLabel day3;
    private javax.swing.JLabel day4;
    private javax.swing.JLabel day5;
    private javax.swing.JLabel day6;
    private javax.swing.JLabel day7;
    private javax.swing.JLabel lacture1;
    private javax.swing.JLabel lacture2;
    private javax.swing.JLabel lacture3;
    private javax.swing.JLabel lacture4;
    private javax.swing.JLabel lacture5;
    private javax.swing.JLabel lacture6;
    // End of variables declaration//GEN-END:variables
}
